//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB_ASP.SalesReport {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalesReport.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NetSalesData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable NetSalesData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NetSalesData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> NetSalesDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalesDatawithArgument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SalesDatawithArgument(string Item, string Qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalesDatawithArgument", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SalesDatawithArgumentAsync(string Item, string Qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalesDatawithItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SalesDatawithItem(string Item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalesDatawithItem", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SalesDatawithItemAsync(string Item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : GB_ASP.SalesReport.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<GB_ASP.SalesReport.WebService1Soap>, GB_ASP.SalesReport.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataTable GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
        
        public System.Data.DataTable NetSalesData() {
            return base.Channel.NetSalesData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> NetSalesDataAsync() {
            return base.Channel.NetSalesDataAsync();
        }
        
        public System.Data.DataTable SalesDatawithArgument(string Item, string Qty) {
            return base.Channel.SalesDatawithArgument(Item, Qty);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SalesDatawithArgumentAsync(string Item, string Qty) {
            return base.Channel.SalesDatawithArgumentAsync(Item, Qty);
        }
        
        public System.Data.DataTable SalesDatawithItem(string Item) {
            return base.Channel.SalesDatawithItem(Item);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SalesDatawithItemAsync(string Item) {
            return base.Channel.SalesDatawithItemAsync(Item);
        }
    }
}
